package edu.berkeley.urel.jms.common;

public class HtmlCleaner {
	public static String cleanHtml(String dirtyHTML) {
		String cleanHTML = "";
		cleanHTML = RemoveCssFromHtml.removeCss(dirtyHTML);

		cleanHTML = cleanHTML
							.replace("\u00A0", "")
							.replace("–", "-")
							.replace("–", "&#8211;")
							.replace("—", "&#8212;")
							.replace("‘", "&#8216;")
							.replace("’", "&#8217;")
							.replace("‚", "&#8218;")
							.replace("“", "&#8220;")
							.replace("”", "&#8221;")
							.replace("„", "&#8222;")
							.replace("†", "&#8224;")
							.replace("‡", "&#8225;")
							.replace("•", "&#8226;")
							.replace("…", "&#8230;")
							.replace("‰", "&#8240;")
							.replace("€", "&#8364;")
							.replace("™", "&#8482;")
							.replace("Œ", "&#338;")
							.replace("œ", "&#339;")
							.replace("Š", "&#352;")
							.replace("š", "&#353;")
							.replace("Ÿ", "&#376;")
							.replace("ƒ", "&#402;")
							.replace("ð", "&#240;")
							.replace("ñ", "&#241;")
							.replace("ò", "&#242;")
							.replace("ó", "&#243;")
							.replace("ô", "&#244;")
							.replace("õ", "&#245;")
							.replace("ö", "&#246;")
							.replace("÷", "&#247;")
							.replace("ø", "&#248;")
							.replace("ù", "&#249;")
							.replace("ú", "&#250;")
							.replace("û", "&#251;")
							.replace("ü", "&#252;")
							.replace("ý", "&#253;")
							.replace("þ", "&#254;")
							.replace("ÿ", "&#255;")
							.replace("à", "&#224;")
							.replace("á", "&#225;")
							.replace("â", "&#226;")
							.replace("ã", "&#227;")
							.replace("ä", "&#228;")
							.replace("å", "&#229;")
							.replace("æ", "&#230;")
							.replace("ç", "&#231;")
							.replace("è", "&#232;")
							.replace("é", "&#233;")
							.replace("ê", "&#234;")
							.replace("ë", "&#235;")
							.replace("ì", "&#236;")
							.replace("í", "&#237;")
							.replace("î", "&#238;")
							.replace("ï", "&#239;")
							.replace("Ð", "&#208;")
							.replace("Ñ", "&#209;")
							.replace("Ò", "&#210;")
							.replace("Ó", "&#211;")
							.replace("Ô", "&#212;")
							.replace("Õ", "&#213;")
							.replace("Ö", "&#214;")
							.replace("×", "&#215;")
							.replace("Ø", "&#216;")
							.replace("Ù", "&#217;")
							.replace("Ú", "&#218;")
							.replace("Û", "&#219;")
							.replace("Ü", "&#220;")
							.replace("Ý", "&#221;")
							.replace("Þ", "&#222;")
							.replace("ß", "&#223;")
							.replace("À", "&#192;")
							.replace("Á", "&#193;")
							.replace("Â", "&#194;")
							.replace("Ã", "&#195;")
							.replace("Ä", "&#196;")
							.replace("Å", "&#197;")
							.replace("Æ", "&#198;")
							.replace("Ç", "&#199;")
							.replace("È", "&#200;")
							.replace("É", "&#201;")
							.replace("Ê", "&#202;")
							.replace("Ë", "&#203;")
							.replace("Ì", "&#204;")
							.replace("Í", "&#205;")
							.replace("Î", "&#206;")
							.replace("Ï", "&#207;")
							.replace("°", "&#176;")
							.replace("±", "&#177;")
							.replace("²", "&#178;")
							.replace("³", "&#179;")
							.replace("´", "&#180;")
							.replace("µ", "&#181;")
							.replace("¶", "&#182;")
							.replace("·", "&#183;")
							.replace("¸", "&#184;")
							.replace("¹", "&#185;")
							.replace("º", "&#186;")
							.replace("»", "&#187;")
							.replace("¼", "&#188;")
							.replace("½", "&#189;")
							.replace("¾", "&#190;")
							.replace("¿", "&#191;")
							.replace("¡", "&#161;")
							.replace("¢", "&#162;")
							.replace("£", "&#163;")
							.replace("¤", "&#164;")
							.replace("¥", "&#165;")
							.replace("¦", "&#166;")
							.replace("§", "&#167;")
							.replace("¨", "&#168;")
							.replace("©", "&#169;")
							.replace("ª", "&#170;")
							.replaceAll("<code>", " ").replace("</code>", "")
							.replace("«", "&#171;")
							.replace("¬", "&#172;")
							.replace("®", "&#174;")
							.replace("¯", "&#175;")
							.replace("�", "")
							.replaceAll(" ", " ")							
							.replace("&nbsp;", " ")
							.replace("&shy;", " ");
							

		return cleanHTML;
	}
	
	public static void main(String[] args) {
		System.out.println("Lead Big Data AnaLead Big Data"
				+ "Customer Care –Trainee  with Quickbooker (ONLY FOR FEMALE CANDIDATES)".replace("–", "&#8211;"));
	}
}

